// Generated by CoffeeScript 1.8.0
var KeyedQueue;

KeyedQueue = function() {
  var instance, queue, store;
  store = Object.create(null);
  queue = [];
  instance = {
    enqueue: function(key, value) {
      if (instance.has(key)) {
        return null;
      }
      queue.push({
        key: key,
        value: value
      });
      store[key] = value;
      return queue.length;
    },
    dequeue: function() {
      var item;
      item = queue.shift();
      delete store[item.key];
      return item.value;
    },
    get: function(key) {
      return store[key];
    },
    has: function(key) {
      return store[key] != null;
    },
    peek: function() {
      if (!queue.length) {
        return void 0;
      }
      return store[queue[0].key];
    },
    size: function() {
      return queue.length;
    }
  };
  return instance;
};

module.exports = KeyedQueue;
